### ISSUE TITLE
Extension not working on flatpak. Error 401 on every play/search

### ISSUE THREAD

**Issue by tr1p0p** [Ovenoboyo/moosync-soundcloud#1]
No of soundcloud songs playing work in moosync with last update.

No playlist playing, no songs playing. And show some weird error about a error 401 on a fil:e path the extension put for no reason : 

![image](https://user-images.githubusercontent.com/37407065/214620729-601b0254-dd9d-4f84-a3b8-944389939b29.png)

Last moosync, last update of the extension.

Cannot add playlist, cannot play anything. Logs show error 401 on basically everything, so something wrong here i suppose.

![image](https://user-images.githubusercontent.com/37407065/214622820-c98a30cf-6ce2-43db-917d-6354bdb4911a.png)

**Comment by tr1p0p** [comment]
Edit : It appear the soundcloud integration not working only in the flatpak version (i'm on last fedora 37).

It work okay on the native package (even if playlist add seem to be broken)

**Comment by Ovenoboyo** [comment]
Sorry for the late reply but this should be fixed from v2.1.2
